export enum EActionType {
  // Group actions 
  JOIN_GROUP_REQUEST = "JOIN_GROUP_REQUEST",
  JOIN_GROUP_REJECTED = "JOIN_GROUP_REJECTED",
  JOINED_GROUP = "JOINED_GROUP",

  // Periodic contribution actions
  PERIODIC_CONTRIBUTION_TRANSACTION_SUCCESS = "PERIODIC_CONTRIBUTION_TRANSACTION_SUCCESS",
  PERIODIC_CONTRIBUTION_TRANSACTION_FAILURE = "PERIODIC_CONTRIBUTION_TRANSACTION_FAILURE",

  // Loan actions
  LOAN_REQUESTED = "LOAN_REQUESTED",
  LOAN_REJECTED = "LOAN_REJECTED",
  LOAN_APPROVED = "LOAN_APPROVED",

  // Periodic earn actions
  RECEIVED_PERIODIC_EARN = "RECEIVED_PERIODIC_EARN",
}