export enum ENotificationType {
  GROUP_JOIN_REQUEST = 'GROUP_JOIN_REQUEST',
  PERIODIC_CONTRIBUTION = 'PERIODIC_CONTRIBUTION',
  LOAN_REQUEST = 'LOAN_REQUEST',
  LOAN = 'LOAN',
  PERIODIC_EARN = 'PERIODIC_EARN',
  CONTRIBUTION_TERM = 'CONTRIBUTION_TERM',
}
