name: Deployment CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
    
